# Generated by Django 4.1 on 2022-08-31 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_moviecollection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
