# Generated by Django 4.1 on 2022-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_remove_moviecollection_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movieapp.movie'),
        ),
    ]
